### PR TITLE
solved multiple counting problem  issue #28

### PR DESCRIPTION
**Pull request by maskmanlucifer**

### CODE REVIEW

**Comment by maskmanlucifer** [comment]
sakib please review changes.

**Comment by maskmanlucifer** [comment]
I have a doubt i did changes for single page only.
I think comapre page was somehow related to this single page so i will do changes in that page too so dont merge this pull request now , i will ask for review once i wll finish editing comapre.js file.

**Comment by sjsakib** [comment]
Please fix the code formatting (spacing, newlines). Try to follow the existing style

**Comment by maskmanlucifer** [comment]
Okk i am reformatting.

**Comment by maskmanlucifer** [comment]
Done with reformatting.

**Comment by maskmanlucifer** [comment]
These changes are for single user data. 
I tested by submitting div 1 and div 2 common problems, results were quite accurate.
Applying same algorithm on compare page is little bit complicated, i can work on that too if you wish.
But i hope for now this single page will work fine with these code changes.

**Comment by sjsakib** [comment]
Sorry for the late response, somehow missed the update. Please format your code with [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode), otherwise, it is hard to tell exactly what changes you made.

**Comment by maskmanlucifer** [comment]
I am forking repo again and creating a new PR. 
I think you formated code and there will be a lot of conflcts if i will create a PR with old commits.

**Pull request closed without merging**
